spring.application.name=damso

server.port=11000

spring.thymeleaf.cache=true
spring.thymeleaf.check-template-location=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

damso.stt.url=${DAMSO_STT_URL:}
damso.llm.url=${DAMSO_LLM_URL:}
damso.llm.model=${DAMSO_LLM_MODEL:}